kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: asparaginase-blast-database
  namespace: krenek-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
